/**
 * training.ts
 *
 * Training management component.
 * Handles animal training records for admin and employee users.
 */

import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { CommonModule, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../services/auth';
import { TrainingService } from '../services/training';

/**
 * Training interface representing a training record
 * Matches the backend data structure for training sessions
 */
export interface Training {
  /** Unique identifier for the training record (auto-generated by MongoDB) */
  _id?: string;
  /** ID of the animal being trained */
  animal_id: string;
  /** Type of rescue training (e.g., Water Rescue, Mountain Rescue) */
  rescue_type: string;
  /** Current status of the training (Scheduled, In Progress, Completed, Cancelled) */
  training_status: string;
  /** Skill level of the training (Beginner, Intermediate, Advanced, Expert) */
  training_level: string;
  /** ID of the trainer assigned to this training */
  trainer_id: string;
  /** Full name of the assigned trainer */
  trainer_name: string;
  /** Date when the training session starts */
  start_date: string | Date;
  /** Date when the training was completed (optional, only set when status is Completed) */
  completion_date?: string | Date;
  /** Performance score achieved in the training (optional, 0-100) */
  score?: number;
  /** Additional notes or observations about the training session */
  notes?: string;
  /** MongoDB timestamps */
  createdAt?: string | Date;
  updatedAt?: string | Date;
}

/**
 * TrainingComponent - Manages the training records UI
 * Allows users to view, add, and interact with training records
 */
@Component({
  selector: 'app-training',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    DatePipe
  ],
  templateUrl: './training.html',
  styleUrl: './training.scss'
})
export class TrainingComponent implements OnInit {

  /**
   * Indicates whether the training form was opened
   * from the animal dashboard.
   * When true, Animal ID is automatically populated
   * and becomes read-only.
   */
  animalSelected: boolean = false;

  /** Array of training records fetched from the backend */
  trainingRecords: Training[] = [];

  /** Stores the ID of the training record being edited */
  editingTrainingId: string | null = null;

  /** New training record form object for creating a new training session */
  newTraining: Training = {
    animal_id: '',
    rescue_type: '',
    training_status: '',
    training_level: '',
    trainer_id: '',
    trainer_name: '',
    start_date: new Date().toISOString().split('T')[0],
    score: undefined,
    notes: ''
  };

  /** Success message displayed after CRUD operations */
  successMessage: string = '';

  /** Error message displayed when CRUD operations fail */
  errorMessage: string = '';

  /**
   * Constructor - injects the TrainingService for API operations
   * @param trainingService - Service for training CRUD operations
   */
  constructor(
    private trainingService: TrainingService,
    public authService: AuthService,
    private cdr: ChangeDetectorRef,
    private router: Router,
    private route: ActivatedRoute
  ) { }

  /**
   * Angular lifecycle hook.
   *
   * Determines whether the component is:
   * - Creating a new training record
   * - Editing an existing training record
   * - Loading training records for a selected animal
   */
  ngOnInit(): void {

    // Check authentication before loading records
    if (!this.authService.isLoggedIn()) {
      console.warn(
        'User is not authenticated.'
      );

      return;
    }

    /*
     * Check route parameter.
     */
    this.route.paramMap.subscribe(params => {

      const id = params.get('id');

      // Existing record - edit mode
      if (id) {
        this.loadTrainingForEdit(id);
        return;
      }

      /*
       * No ID means this is a new training record.
       * Check if an animal was selected from dashboard.
       */
      this.route.queryParams.subscribe(query => {
        const animalId = query['animal_id'];

        if (animalId) {
          this.newTraining.animal_id = animalId;
          this.animalSelected = true;
        }
      });

      // Load existing records if needed
      this.loadTraining();
    });
  }

  /**
   * Fetches all training records from the backend
   * Updates the trainingRecords array with the retrieved data
   * Logs errors to console if the request fails
   */
  loadTraining(): void {
    this.trainingService.getTraining()
      .subscribe({
        next: (data) => {
          this.trainingRecords = data;
          this.cdr.detectChanges(); // Force UI refresh after async data update
        },
        error: (error) => {
          console.error('Failed to load training records', error);
          this.trainingRecords = [];
        }
      });
  }

  /**
   * Loads training records for one specific animal.
   * Used when the Training page is opened from the Dashboard Train button.
   *
   * @param animalId - Animal ID received from dashboard query parameters
   */
  loadAnimalTraining(animalId: string): void {

    this.trainingService
      .getAnimalTraining(animalId)
      .subscribe({
        next: (data) => {
          this.trainingRecords = data;
          this.cdr.detectChanges();
        },

        error: (error) => {
          console.error(
            'Failed to load animal training history',
            error
          );
          this.trainingRecords = [];
        }
      });
  }

  /**
   * Loads one training record into the form.
   *
   * Used when editing an existing training record.
   *
   * @param id MongoDB training record ID
   */
  loadTrainingForEdit(id: string): void {
    this.trainingService
      .getTrainingById(id)
      .subscribe({

        next: (training) => {
          this.editingTrainingId = training._id ?? null;

          this.newTraining = {

            animal_id: training.animal_id,
            rescue_type: training.rescue_type,
            training_status: training.training_status,
            training_level: training.training_level,
            trainer_id: training.trainer_id,
            trainer_name: training.trainer_name,
            start_date:
              this.formatDateForInput(
                training.start_date
              ),
            completion_date:
              training.completion_date
                ? this.formatDateForInput(
                  training.completion_date
                )
                : undefined,
            score: training.score,
            notes: training.notes
          };

          this.animalSelected = true;
          this.loadAnimalTraining(
            training.animal_id
          );
          this.cdr.detectChanges();
        },

        error: (error) => {

          console.error('Failed to load training record', error);

          this.errorMessage = 'Failed to load training record.';
        }
      });
  }

  /**
   * Refreshes training history while preserving current view.
   * Loads only the selected animal history when opened from dashboard.
   * Otherwise loads all training records.
   */
  refreshTrainingHistory(): void {

    if (this.animalSelected && this.newTraining.animal_id) {
      this.loadAnimalTraining(
        this.newTraining.animal_id
      );

    } else {
      this.loadTraining();
    }
  }

  /**
   * Creates a new training record or updates an existing one.
   * Uses editingTrainingId to determine the operation.
   */
  addTraining(): void {

    // Update existing record
    if (this.editingTrainingId) {

      this.trainingService.updateTraining(
        this.editingTrainingId,
        this.newTraining
      )
        .subscribe({
          next: () => {
            this.successMessage = 'Training record updated successfully.';
            this.errorMessage = '';
            this.refreshTrainingHistory();
            this.resetForm();
            this.cdr.detectChanges();
          },

          error: (error) => {
            console.error(
              'Failed to update training record',
              error
            );

            this.errorMessage =
              error.error?.message ||
              'Failed to update training record. Please try again.';
            this.successMessage = '';
          }
        });
    }

    // Create new record
    else {
      this.trainingService.createTraining(
        this.newTraining
      )
        .subscribe({
          next: () => {
            this.successMessage = 'Training record created successfully.';
            this.errorMessage = '';
            this.refreshTrainingHistory();
            this.resetForm();
            this.cdr.detectChanges();
          },

          error: (error) => {
            console.error(
              'Failed to create training record',
              error
            );

            this.errorMessage =
              error.error?.message ||
              'Failed to create training record. Please try again.';
            this.successMessage = '';
          }
        });
    }
  }

  /**
   * Loads an existing training record into the form for editing.
   * Converts dates into the format required by HTML date inputs.
   *
   * @param training - Training record selected from the table
   */
  editTraining(training: Training): void {

    this.editingTrainingId = training._id ?? null;

    // Update existing object instead of replacing it
    this.newTraining.animal_id = training.animal_id;
    this.newTraining.rescue_type = training.rescue_type;
    this.newTraining.training_status = training.training_status;
    this.newTraining.training_level = training.training_level;
    this.newTraining.trainer_id = training.trainer_id;
    this.newTraining.trainer_name = training.trainer_name;
    this.newTraining.start_date = this.formatDateForInput(training.start_date);

    this.newTraining.completion_date =
      training.completion_date
        ? this.formatDateForInput(training.completion_date)
        : undefined;

    this.newTraining.score = training.score;
    this.newTraining.notes = training.notes;

    this.cdr.detectChanges();
    console.log('FORM DATA:', this.newTraining);
  }

  /**
 * Converts MongoDB date format into HTML date input format.
 * Example:
 * 2026-07-26T00:00:00.000Z -> 2026-07-26
 */
  private formatDateForInput(date: string | Date): string {

    return new Date(date)
      .toISOString()
      .split('T')[0];
  }

  /**
   * Navigates to edit page for selected training record.
   *
   * @param id - Training record MongoDB ID
   */
  goToEdit(id: string | undefined): void {

    if (!id) {
      console.error('Training record has no ID');
      return;
    }

    this.router.navigate([
      '/admin/training/edit',
      id
    ]);

  }

  /**
   * Deletes a training record
   * Confirms deletion before removing the record
   */
  deleteTraining(id: string): void {

    if (!confirm('Delete this training record?')) {
      return;
    }

    this.trainingService.deleteTraining(id)
      .subscribe({
        next: () => {
          this.successMessage = 'Training record deleted successfully.';
          this.errorMessage = '';
          this.refreshTrainingHistory();
          this.cdr.detectChanges();
        },

        error: (error) => {
          console.error(
            'Failed to delete training record',
            error
          );

          this.errorMessage =
            error.error?.message ||
            'Failed to delete training record.';
        }
      });
  }

  /**
   * Resets the newTraining form to its default state
   * Clears all fields and sets default values
   * Called after successful creation or when user cancels
   */
  resetForm(): void {
    this.newTraining = {
      animal_id: '',
      rescue_type: '',
      training_status: '',
      training_level: '',
      trainer_id: '',
      trainer_name: '',
      start_date: new Date().toISOString().split('T')[0],
      notes: ''
    };

    this.editingTrainingId = null;
  }

  /**
   * Go back to the training history page.
   */
  goBackToHistory(): void {
    if (this.newTraining.animal_id) {
      this.router.navigate(
        ['/training-history'],
        {
          queryParams: {
            animal_id: this.newTraining.animal_id
          }
        }
      );

    } else {
      this.router.navigate(
        ['/training-history']
      );
    }
  }
}
